### ISSUE TITLE
More control on who can view

### ISSUE THREAD

**Issue by Diginari** [janvanhelvoort/Umbraco-hide-properties#5]
Thanks for the package Jan, looks perfect for what I need, however I need a little more control over who can see the fields/tabs.

At the moment if you select a user group it is hidden if that user is part of that group, however if the user is also part of a group that is allowed, it's still hidden - can we have this functionality modified? I.e. I would find it easier to add a user to a specific group to allow them to view, they may well be an admin but I may not want them to see the property/tab unless they are part of a specific group.

**Comment by janvanhelvoort** [comment]
I think you will need to look it from the other side, everyone can see everything, all tabs and properties. I would create a user group, or use the build in, `Sensitive data`. Then apply users to that group and hide the specific tabs and properties for this group.

Likely, you have more tabs and properties that would be visible for everyone, than that you would hide?

**Comment by Diginari** [comment]
Thanks, that works. I guess I need to remember to add anyone new into that group to hide it from them rather than giving the permissions to it. Will work though.

Thanks for your contrib again

**Comment by janvanhelvoort** [comment]
When you invite or create a new user, you must add them to a user group. At that moment,  you could select the right users groups.
